apiVersion: v1
kind: Pod
metadata:
  name: ebs
spec:
  containers:
    - image: centos:7
      name: centos
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /test-ebs1
          name: test-volume
  volumes:
    - name: test-volume
      awsElasticBlockStore:
        volumeID: vol-0b4643348451e5a32
        fsType: ext4