apiVersion: v1 
kind: Pod 
metadata:
  name: empty-dir

spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}