apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
    - image: centos:7
      name: centos
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /cache
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /data
        type: Directory