apiVersion: v1
kind: Pod 
metadata:
  name: pod05

spec:
  containers:
    - name : nginx
      image: nginx
      resources:
        requests:
          memory: "256Mi"
          cpu: "250"
        limits:
          cpu: "200m"
          memory: "400Mi"